version: '3.7'
services:
  mongodb:
    image: mongo:4.2.8
    container_name: mongodb
    # Seed the database for initialization
    entrypoint: ["bash", "mongo lichess /home/lila/bin/mongodb/indexes.js"]
    volumes:
      - $LILA_REPOSITORY_DIR:/home/lila:delegated

  redis:
    image: redis:6.0.5

  lila:
    build:
      context: .
    entrypoint: ["bash", "/home/lichess/run.sh"]
    working_dir: /home/lichess/lila
    environment:
      - LILA_LOCATION=/home/lichess/lila
      - LILA_UI_LOCATION=/home/lichess/lila/ui
      - SBT_OPTS=
        -Dmongodb.uri=mongodb://mongodb:27017/lichess
        -Dredis.uri=redis://redis:6379
    volumes:
      - $LILA_REPOSITORY_DIR:/home/lichess/lila:delegated
    ports:
      - 9663:9663
    depends_on:
      - mongodb
      - redis

  lila-ws:
    build:
      context: .
    working_dir: /lila-ws
    entrypoint: ["sbt", "run"]
    environment:
      - SBT_OPTS=
        -Dmongodb.uri=mongodb://mongodb:27017/lichess
        -Dredis.uri=redis://redis:6379
    volumes:
      - $LILA_WS_REPOSITORY_DIR:/lila-ws:delegated
    ports:
      - 9664:9664
    depends_on:
      - mongodb
      - redis
      - lila
